POST http://localhost:5000/users/register
Content-Type : application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM2OWE2ZjVlLTAzZGEtNDgyYi1iZDcwLWViMTExOWEyNTVmNyIsImVtYWlsIjoicm9iYXlhdEBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTk2MDQ1MTAsImV4cCI6MTc1OTYwODExMCwiYXVkIjoibG9jYWxob3N0OjUwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6NTAwMCJ9.qyHT5uOkGvYamb8QmKWy-x-D90iL8FL2MLvPeFPpnfo

{
    "name" : "Farsit",
    "email" : "robayasdtsdf1dd61@gmail.com",
    "password" : "Farsit@2025"
}
